#!/usr/bin/env bash

# Arch-repo packages
sudo pacman -S sudo neovim xorg ly git base-devel xmonad xmonad-contrib \
xmobar pcmanfm pacman-contrib nitrogen dmenu fish alacritty picom mpv \
yt-dlp gvfs htop lsd bat xcursor-themes vifm scrot xclip libnotify \
notification-daemon udisks2 gparted ttf-inconsolata ttf-hack ttf-monofur \
terminus-font ttf-ubuntu-font-family ttf-cascadia-code ttf-fira-code \
ttf-ubuntu-mono-nerd alsa-utils xsettingsd pipewire pipewire-alsa \
pipewire-pulse wireplumber bluez bluez-utils xf86-input-synaptics \
ttf-liberation ttf-dejavu unzip

# AUR install
git clone https://aur.archlinux.org/aura-bin.git
cd aura-bin
makepkg
sudo pacman -U *.zst

# AUR packages
aura -A mutt-wizard-git brave-bin pfetch ttf-comic-mono-git \
pcloud-drive jmtpfs kanata-bin
