#!/usr/bin/env bash
set -e
set -x

# Arch-repo packages
sudo pacman -S sudo neovim ly git xmonad xmonad-contrib xmobar pcmanfm pacman-contrib fish alacritty picom mpv yt-dlp gvfs lsd bat xcursor-themes vifm scrot xclip cronie libnotify notification-daemon udisks2 gparted ttf-inconsolata ttf-hack ttf-monofur terminus-font ttf-ubuntu-mono-nerd ttf-cascadia-code ttf-fira-code

# AUR
git clone https://aur.archlinux.org/aura-bin.git
cd aura-bin
makepkg
sudo pacman -U *.zst

# AUR packages
sudo aura -A ark-icon-theme nvim-packer-git mutt-wizard-git pam-gnupg brillo ttf-comic-mono-git
