#!/usr/bin/env bash

# Arch-repo packages
sudo pacman -S xorg ly base-devel xmonad xmonad-contrib xmobar \
pcmanfm pacman-contrib nitrogen dmenu fish alacritty picom mpv \
yt-dlp gvfs htop lsd bat xcursor-themes vifm scrot xclip libnotify \
notification-daemon udisks2 gparted ttf-inconsolata ttf-hack ttf-monofur \
terminus-font ttf-ubuntu-font-family ttf-cascadia-code ttf-fira-code \
ttf-ubuntu-mono-nerd alsa-utils xsettingsd pipewire pipewire-alsa \
pipewire-pulse wireplumber bluez bluez-utils xf86-input-synaptics \
ttf-liberation ttf-dejavu unzip xorg-xmessage libreoffice-fresh \
luarocks shellcheck dunst playerctl mpv-mpris

# AUR install
git clone https://aur.archlinux.org/aura-bin.git
cd aura-bin
makepkg
sudo pacman -U *.zst

# AUR packages
aura -A brave-bin kanata-bin pfetch ttf-comic-mono-git \
ttf-noto-emoji-monochrome ttf-times-new-roman\

# Fnm install
curl -fsSL https://fnm.vercel.app/install | bash
